inherit_from: ./configs/Static/seven_scenes/seven_scenes.yaml
scene: redkitchen

data:
  input_folder: ROOT_FOLDER_PLACEHOLDER/redkitchen
cam:
  H: 480 
  W: 640 
  fx: 585.0
  fy: 585.0
  cx: 320.0
  cy: 240.0
